youtubeChannelDict = {

    18: "Short Movies",
    21: "Videoblogging",
    30: "Movies",
    31: "Anime/Animation",
    32: "Action/Adventure",
    33: "Classics",
    34: "Comedy",
    35: "Documentary",
    36: "Drama",
    37: "Family",
    38: "Foreign",
    39: "Horror",
    40: "Sci-Fi/Fantasy",
    41: "Thriller",
    42: "Shorts",
    43: "Shows",
    44: "Trailers",
    2: "Cars & Vehicles",
    23: "Comedy",
    27: "Education",
    24: "Entertainment",
    1: "Film & Animation",
    20: "Gaming",
    26: "How-to & Style",
    10: "Music",
    25: "News & Politics",
    29: "Non-profits & Activism",
    22: "People & Blogs",
    15: "Pets & Animals",
    28: "Science & Technology",
    17: "Sport",
    19: "Travel & Events",

}
