import base_youtube_code
import keyword_search
import get_channel_videos
import video_statistics
import get_channel_stats
import sqlite3

# run file to start function flow



kw = keywords = [


'dead by daylight beginner guide',
'dead by daylight beginner tutorial',
'dead by daylight beginner strategy',
'dead by daylight beginner methods',
'dead by daylight beginner lessons',
'dead by daylight beginner techniques',
'dead by daylight beginner videos',
'dead by daylight beginner lessons',
'dead by daylight beginner tactics',
'dead by daylight beginner overview',
'dead by daylight beginner tips and trick',
'dead by daylight beginner gameplay',
'dead by daylight beginner common mistakes',
'dead by daylight beginner builds',
'dead by daylight beginner players',
'dead by daylight beginner noobs',
'dead by daylight beginner news',
'dead by daylight tutorial',
'dead by daylight intermediate guide',
'dead by daylight intermediate tutorial',
'dead by daylight intermediate strategy',
'dead by daylight intermediate methods',
'dead by daylight intermediate lessons',
'dead by daylight intermediate techniques',
'dead by daylight intermediate videos',
'dead by daylight intermediate lessons',
'dead by daylight intermediate tactics',
'dead by daylight intermediate overview',
'dead by daylight intermediate tips and trick',
'dead by daylight intermediate gameplay',
'dead by daylight intermediate common mistakes',
'dead by daylight intermediate builds',
'dead by daylight intermediate players',
'dead by daylight intermediate noobs',
'dead by daylight intermediate news',
'dead by daylight intermediate tutorial',
'dead by daylight expert guide',
'dead by daylight expert tutorial',
'dead by daylight expert strategy',
'dead by daylight expert methods',
'dead by daylight expert lessons',
'dead by daylight expert techniques',
'dead by daylight expert videos',
'dead by daylight expert lessons',
'dead by daylight expert tactics',
'dead by daylight expert overview',
'dead by daylight expert tips and trick',
'dead by daylight expert gameplay',
'dead by daylight expert common mistakes',
'dead by daylight expert builds',
'dead by daylight expert players',
'dead by daylight expert noobs',
'dead by daylight expert news',
'dead by daylight expert tutorial',
'dead by daylight pro guide',
'dead by daylight pro tutorial',
'dead by daylight pro strategy',
'dead by daylight pro methods',
'dead by daylight pro lessons',
'dead by daylight pro techniques',
'dead by daylight pro videos',
'dead by daylight pro lessons',
'dead by daylight pro tactics',
'dead by daylight pro overview',
'dead by daylight pro tips and trick',
'dead by daylight pro gameplay',
'dead by daylight pro common mistakes',
'dead by daylight pro builds',
'dead by daylight pro players',
'dead by daylight pro noobs',
'dead by daylight pro news',
'dead by daylight pro tutorial',
'dark souls beginner guide',
'dark souls beginner tutorial',
'dark souls beginner strategy',
'dark souls beginner methods',
'dark souls beginner lessons',
'dark souls beginner techniques',
'dark souls beginner videos',
'dark souls beginner lessons',
'dark souls beginner tactics',
'dark souls beginner overview',
'dark souls beginner tips and trick',
'dark souls beginner gameplay',
'dark souls beginner common mistakes',
'dark souls beginner builds',
'dark souls beginner players',
'dark souls beginner noobs',
'dark souls beginner news',
'dark souls tutorial',
'dark souls intermediate guide',
'dark souls intermediate tutorial',
'dark souls intermediate strategy',
'dark souls intermediate methods',
'dark souls intermediate lessons',
'dark souls intermediate techniques',
'dark souls intermediate videos',
'dark souls intermediate lessons',
'dark souls intermediate tactics',
'dark souls intermediate overview',
'dark souls intermediate tips and trick',
'dark souls intermediate gameplay',
'dark souls intermediate common mistakes',
'dark souls intermediate builds',
'dark souls intermediate players',
'dark souls intermediate noobs',
'dark souls intermediate news',
'dark souls intermediate tutorial',
'dark souls expert guide',
'dark souls expert tutorial',
'dark souls expert strategy',
'dark souls expert methods',
'dark souls expert lessons',
'dark souls expert techniques',
'dark souls expert videos',
'dark souls expert lessons',
'dark souls expert tactics',
'dark souls expert overview',
'dark souls expert tips and trick',
'dark souls expert gameplay',
'dark souls expert common mistakes',
'dark souls expert builds',
'dark souls expert players',
'dark souls expert noobs',
'dark souls expert news',
'dark souls expert tutorial',
'dark souls pro guide',
'dark souls pro tutorial',
'dark souls pro strategy',
'dark souls pro methods',
'dark souls pro lessons',
'dark souls pro techniques',
'dark souls pro videos',
'dark souls pro lessons',
'dark souls pro tactics',
'dark souls pro overview',
'dark souls pro tips and trick',
'dark souls pro gameplay',
'dark souls pro common mistakes',
'dark souls pro builds',
'dark souls pro players',
'dark souls pro noobs',
'dark souls pro news',
'dark souls pro tutorial',
'dead cells beginner guide',
'dead cells beginner tutorial',
'dead cells beginner strategy',
'dead cells beginner methods',
'dead cells beginner lessons',
'dead cells beginner techniques',
'dead cells beginner videos',
'dead cells beginner lessons',
'dead cells beginner tactics',
'dead cells beginner overview',
'dead cells beginner tips and trick',
'dead cells beginner gameplay',
'dead cells beginner common mistakes',
'dead cells beginner builds',
'dead cells beginner players',
'dead cells beginner noobs',
'dead cells beginner news',
'dead cells tutorial',
'dead cells intermediate guide',
'dead cells intermediate tutorial',
'dead cells intermediate strategy',
'dead cells intermediate methods',
'dead cells intermediate lessons',
'dead cells intermediate techniques',
'dead cells intermediate videos',
'dead cells intermediate lessons',
'dead cells intermediate tactics',
'dead cells intermediate overview',
'dead cells intermediate tips and trick',
'dead cells intermediate gameplay',
'dead cells intermediate common mistakes',
'dead cells intermediate builds',
'dead cells intermediate players',
'dead cells intermediate noobs',
'dead cells intermediate news',
'dead cells intermediate tutorial',
'dead cells expert guide',
'dead cells expert tutorial',
'dead cells expert strategy',
'dead cells expert methods',
'dead cells expert lessons',
'dead cells expert techniques',
'dead cells expert videos',
'dead cells expert lessons',
'dead cells expert tactics',
'dead cells expert overview',
'dead cells expert tips and trick',
'dead cells expert gameplay',
'dead cells expert common mistakes',
'dead cells expert builds',
'dead cells expert players',
'dead cells expert noobs',
'dead cells expert news',
'dead cells expert tutorial',
'dead cells pro guide',
'dead cells pro tutorial',
'dead cells pro strategy',
'dead cells pro methods',
'dead cells pro lessons',
'dead cells pro techniques',
'dead cells pro videos',
'dead cells pro lessons',
'dead cells pro tactics',
'dead cells pro overview',
'dead cells pro tips and trick',
'dead cells pro gameplay',
'dead cells pro common mistakes',
'dead cells pro builds',
'dead cells pro players',
'dead cells pro noobs',
'dead cells pro news',
'dead cells pro tutorial',
'black desert online beginner guide',
'black desert online beginner tutorial',
'black desert online beginner strategy',
'black desert online beginner methods',
'black desert online beginner lessons',
'black desert online beginner techniques',
'black desert online beginner videos',
'black desert online beginner lessons',
'black desert online beginner tactics',
'black desert online beginner overview',
'black desert online beginner tips and trick',
'black desert online beginner gameplay',
'black desert online beginner common mistakes',
'black desert online beginner builds',
'black desert online beginner players',
'black desert online beginner noobs',
'black desert online beginner news',
'black desert online tutorial',
'black desert online intermediate guide',
'black desert online intermediate tutorial',
'black desert online intermediate strategy',
'black desert online intermediate methods',
'black desert online intermediate lessons',
'black desert online intermediate techniques',
'black desert online intermediate videos',
'black desert online intermediate lessons',
'black desert online intermediate tactics',
'black desert online intermediate overview',
'black desert online intermediate tips and trick',
'black desert online intermediate gameplay',
'black desert online intermediate common mistakes',
'black desert online intermediate builds',
'black desert online intermediate players',
'black desert online intermediate noobs',
'black desert online intermediate news',
'black desert online intermediate tutorial',
'black desert online expert guide',
'black desert online expert tutorial',
'black desert online expert strategy',
'black desert online expert methods',
'black desert online expert lessons',
'black desert online expert techniques',
'black desert online expert videos',
'black desert online expert lessons',
'black desert online expert tactics',
'black desert online expert overview',
'black desert online expert tips and trick',
'black desert online expert gameplay',
'black desert online expert common mistakes',
'black desert online expert builds',
'black desert online expert players',
'black desert online expert noobs',
'black desert online expert news',
'black desert online expert tutorial',
'black desert online pro guide',
'black desert online pro tutorial',
'black desert online pro strategy',
'black desert online pro methods',
'black desert online pro lessons',
'black desert online pro techniques',
'black desert online pro videos',
'black desert online pro lessons',
'black desert online pro tactics',
'black desert online pro overview',
'black desert online pro tips and trick',
'black desert online pro gameplay',
'black desert online pro common mistakes',
'black desert online pro builds',
'black desert online pro players',
'black desert online pro noobs',
'black desert online pro news',
'black desert online pro tutorial',
'far cry 5 beginner guide',
'far cry 5 beginner tutorial',
'far cry 5 beginner strategy',
'far cry 5 beginner methods',
'far cry 5 beginner lessons',
'far cry 5 beginner techniques',
'far cry 5 beginner videos',
'far cry 5 beginner lessons',
'far cry 5 beginner tactics',
'far cry 5 beginner overview',
'far cry 5 beginner tips and trick',
'far cry 5 beginner gameplay',
'far cry 5 beginner common mistakes',
'far cry 5 beginner builds',
'far cry 5 beginner players',
'far cry 5 beginner noobs',
'far cry 5 beginner news',
'far cry 5 tutorial',
'far cry 5 intermediate guide',
'far cry 5 intermediate tutorial',
'far cry 5 intermediate strategy',
'far cry 5 intermediate methods',
'far cry 5 intermediate lessons',
'far cry 5 intermediate techniques',
'far cry 5 intermediate videos',
'far cry 5 intermediate lessons',
'far cry 5 intermediate tactics',
'far cry 5 intermediate overview',
'far cry 5 intermediate tips and trick',
'far cry 5 intermediate gameplay',
'far cry 5 intermediate common mistakes',
'far cry 5 intermediate builds',
'far cry 5 intermediate players',
'far cry 5 intermediate noobs',
'far cry 5 intermediate news',
'far cry 5 intermediate tutorial',
'far cry 5 expert guide',
'far cry 5 expert tutorial',
'far cry 5 expert strategy',
'far cry 5 expert methods',
'far cry 5 expert lessons',
'far cry 5 expert techniques',
'far cry 5 expert videos',
'far cry 5 expert lessons',
'far cry 5 expert tactics',
'far cry 5 expert overview',
'far cry 5 expert tips and trick',
'far cry 5 expert gameplay',
'far cry 5 expert common mistakes',
'far cry 5 expert builds',
'far cry 5 expert players',
'far cry 5 expert noobs',
'far cry 5 expert news',
'far cry 5 expert tutorial',
'far cry 5 pro guide',
'far cry 5 pro tutorial',
'far cry 5 pro strategy',
'far cry 5 pro methods',
'far cry 5 pro lessons',
'far cry 5 pro techniques',
'far cry 5 pro videos',
'far cry 5 pro lessons',
'far cry 5 pro tactics',
'far cry 5 pro overview',
'far cry 5 pro tips and trick',
'far cry 5 pro gameplay',
'far cry 5 pro common mistakes',
'far cry 5 pro builds',
'far cry 5 pro players',
'far cry 5 pro noobs',
'far cry 5 pro news',
'far cry 5 pro tutorial',
'minecraft beginner guide',
'minecraft beginner tutorial',
'minecraft beginner strategy',
'minecraft beginner methods',
'minecraft beginner lessons',
'minecraft beginner techniques',
'minecraft beginner videos',
'minecraft beginner lessons',
'minecraft beginner tactics',
'minecraft beginner overview',
'minecraft beginner tips and trick',
'minecraft beginner gameplay',
'minecraft beginner common mistakes',
'minecraft beginner builds',
'minecraft beginner players',
'minecraft beginner noobs',
'minecraft beginner news',
'minecraft tutorial',
'minecraft intermediate guide',
'minecraft intermediate tutorial',
'minecraft intermediate strategy',
'minecraft intermediate methods',
'minecraft intermediate lessons',
'minecraft intermediate techniques',
'minecraft intermediate videos',
'minecraft intermediate lessons',
'minecraft intermediate tactics',
'minecraft intermediate overview',
'minecraft intermediate tips and trick',
'minecraft intermediate gameplay',
'minecraft intermediate common mistakes',
'minecraft intermediate builds',
'minecraft intermediate players',
'minecraft intermediate noobs',
'minecraft intermediate news',
'minecraft intermediate tutorial',
'minecraft expert guide',
'minecraft expert tutorial',
'minecraft expert strategy',
'minecraft expert methods',
'minecraft expert lessons',
'minecraft expert techniques',
'minecraft expert videos',
'minecraft expert lessons',
'minecraft expert tactics',
'minecraft expert overview',
'minecraft expert tips and trick',
'minecraft expert gameplay',
'minecraft expert common mistakes',
'minecraft expert builds',
'minecraft expert players',
'minecraft expert noobs',
'minecraft expert news',
'minecraft expert tutorial',
'minecraft pro guide',
'minecraft pro tutorial',
'minecraft pro strategy',
'minecraft pro methods',
'minecraft pro lessons',
'minecraft pro techniques',
'minecraft pro videos',
'minecraft pro lessons',
'minecraft pro tactics',
'minecraft pro overview',
'minecraft pro tips and trick',
'minecraft pro gameplay',
'minecraft pro common mistakes',
'minecraft pro builds',
'minecraft pro players',
'minecraft pro noobs',
'minecraft pro news',
'minecraft pro tutorial',


    ]

if __name__ == '__main__':
    base_youtube_code.os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'
    client = base_youtube_code.get_authenticated_service()
    # NEED TO PASS IN CLIENT INTO FUNCTIONS!

    # get a list of channel IDs related to keywork

    for keyword in kw:
        channelId_list = keyword_search.run_keyword_search(client,keyword)

        # if channelId exist in database:
        # do not run

        for channelId in channelId_list:
            connection = sqlite3.connect('core.db')
            c = connection.cursor()
            creatorIdTuple = (channelId,)

            c.execute("""
                SELECT * FROM video
                WHERE creatorID = ?
                """, creatorIdTuple)

            existing_videoCount = c.fetchall()

            connection.commit()
            connection.close()

            # if there is a result in DB, have videos from creator saved
            if len(existing_videoCount) > 0:
                print('already discovered')
            # if results == 0, no videos saved from creator, just discovered a new creator
            else:
                videoId_list = get_channel_videos.run_get_channel_videos(client, channelId)
                for videoId in videoId_list:
                    video_statistics.run_video_statistics(client, videoId)
                print('new creator discovered')
                get_channel_stats.runStats(channelId)




