import base_youtube_code
import keyword_search
import get_channel_videos
import video_statistics
import get_channel_stats
import sqlite3

# run file to start function flow

# IMPORTANT IMPORTANT IMPORTANT IMPORTANT

#########################################################
#########################################################
#########################################################
####REMEMBER TO RECORD THE REFERENCE NUMBERS INSIDE SCRATCH PAD#####################
#########################################################


kw = keywords = [


'super smash bros beginner guide',
'super smash bros beginner tutorial',
'super smash bros beginner strategy',
'super smash bros beginner methods',
'super smash bros beginner lessons',
'super smash bros beginner techniques',
'super smash bros beginner videos',
'super smash bros beginner lessons',
'super smash bros beginner tactics',
'super smash bros beginner overview',
'super smash bros beginner tips and trick',
'super smash bros beginner gameplay',
'super smash bros beginner common mistakes',
'super smash bros beginner builds',
'super smash bros beginner players',
'super smash bros beginner noobs',
'super smash bros beginner news',
'super smash bros tutorial',
'super smash bros intermediate guide',
'super smash bros intermediate tutorial',
'super smash bros intermediate strategy',
'super smash bros intermediate methods',
'super smash bros intermediate lessons',
'super smash bros intermediate techniques',
'super smash bros intermediate videos',
'super smash bros intermediate lessons',
'super smash bros intermediate tactics',
'super smash bros intermediate overview',
'super smash bros intermediate tips and trick',
'super smash bros intermediate gameplay',
'super smash bros intermediate common mistakes',
'super smash bros intermediate builds',
'super smash bros intermediate players',
'super smash bros intermediate noobs',
'super smash bros intermediate news',
'super smash bros intermediate tutorial',
'super smash bros expert guide',
'super smash bros expert tutorial',
'super smash bros expert strategy',
'super smash bros expert methods',
'super smash bros expert lessons',
'super smash bros expert techniques',
'super smash bros expert videos',
'super smash bros expert lessons',
'super smash bros expert tactics',
'super smash bros expert overview',
'super smash bros expert tips and trick',
'super smash bros expert gameplay',
'super smash bros expert common mistakes',
'super smash bros expert builds',
'super smash bros expert players',
'super smash bros expert noobs',
'super smash bros expert news',
'super smash bros expert tutorial',
'super smash bros pro guide',
'super smash bros pro tutorial',
'super smash bros pro strategy',
'super smash bros pro methods',
'super smash bros pro lessons',
'super smash bros pro techniques',
'super smash bros pro videos',
'super smash bros pro lessons',
'super smash bros pro tactics',
'super smash bros pro overview',
'super smash bros pro tips and trick',
'super smash bros pro gameplay',
'super smash bros pro common mistakes',
'super smash bros pro builds',
'super smash bros pro players',
'super smash bros pro noobs',
'super smash bros pro news',
'super smash bros pro tutorial',
'marvel vs capcom beginner guide',
'marvel vs capcom beginner tutorial',
'marvel vs capcom beginner strategy',
'marvel vs capcom beginner methods',
'marvel vs capcom beginner lessons',
'marvel vs capcom beginner techniques',
'marvel vs capcom beginner videos',
'marvel vs capcom beginner lessons',
'marvel vs capcom beginner tactics',
'marvel vs capcom beginner overview',
'marvel vs capcom beginner tips and trick',
'marvel vs capcom beginner gameplay',
'marvel vs capcom beginner common mistakes',
'marvel vs capcom beginner builds',
'marvel vs capcom beginner players',
'marvel vs capcom beginner noobs',
'marvel vs capcom beginner news',
'marvel vs capcom tutorial',
'marvel vs capcom intermediate guide',
'marvel vs capcom intermediate tutorial',
'marvel vs capcom intermediate strategy',
'marvel vs capcom intermediate methods',
'marvel vs capcom intermediate lessons',
'marvel vs capcom intermediate techniques',
'marvel vs capcom intermediate videos',
'marvel vs capcom intermediate lessons',
'marvel vs capcom intermediate tactics',
'marvel vs capcom intermediate overview',
'marvel vs capcom intermediate tips and trick',
'marvel vs capcom intermediate gameplay',
'marvel vs capcom intermediate common mistakes',
'marvel vs capcom intermediate builds',
'marvel vs capcom intermediate players',
'marvel vs capcom intermediate noobs',
'marvel vs capcom intermediate news',
'marvel vs capcom intermediate tutorial',
'marvel vs capcom expert guide',
'marvel vs capcom expert tutorial',
'marvel vs capcom expert strategy',
'marvel vs capcom expert methods',
'marvel vs capcom expert lessons',
'marvel vs capcom expert techniques',
'marvel vs capcom expert videos',
'marvel vs capcom expert lessons',
'marvel vs capcom expert tactics',
'marvel vs capcom expert overview',
'marvel vs capcom expert tips and trick',
'marvel vs capcom expert gameplay',
'marvel vs capcom expert common mistakes',
'marvel vs capcom expert builds',
'marvel vs capcom expert players',
'marvel vs capcom expert noobs',
'marvel vs capcom expert news',
'marvel vs capcom expert tutorial',
'marvel vs capcom pro guide',
'marvel vs capcom pro tutorial',
'marvel vs capcom pro strategy',
'marvel vs capcom pro methods',
'marvel vs capcom pro lessons',
'marvel vs capcom pro techniques',
'marvel vs capcom pro videos',
'marvel vs capcom pro lessons',
'marvel vs capcom pro tactics',
'marvel vs capcom pro overview',
'marvel vs capcom pro tips and trick',
'marvel vs capcom pro gameplay',
'marvel vs capcom pro common mistakes',
'marvel vs capcom pro builds',
'marvel vs capcom pro players',
'marvel vs capcom pro noobs',
'marvel vs capcom pro news',
'marvel vs capcom pro tutorial',
' tekken beginner guide',
' tekken beginner tutorial',
' tekken beginner strategy',
' tekken beginner methods',
' tekken beginner lessons',
' tekken beginner techniques',
' tekken beginner videos',
' tekken beginner lessons',
' tekken beginner tactics',
' tekken beginner overview',
' tekken beginner tips and trick',
' tekken beginner gameplay',
' tekken beginner common mistakes',
' tekken beginner builds',
' tekken beginner players',
' tekken beginner noobs',
' tekken beginner news',
' tekken tutorial',
' tekken intermediate guide',
' tekken intermediate tutorial',
' tekken intermediate strategy',
' tekken intermediate methods',
' tekken intermediate lessons',
' tekken intermediate techniques',
' tekken intermediate videos',
' tekken intermediate lessons',
' tekken intermediate tactics',
' tekken intermediate overview',
' tekken intermediate tips and trick',
' tekken intermediate gameplay',
' tekken intermediate common mistakes',
' tekken intermediate builds',
' tekken intermediate players',
' tekken intermediate noobs',
' tekken intermediate news',
' tekken intermediate tutorial',
' tekken expert guide',
' tekken expert tutorial',
' tekken expert strategy',
' tekken expert methods',
' tekken expert lessons',
' tekken expert techniques',
' tekken expert videos',
' tekken expert lessons',
' tekken expert tactics',
' tekken expert overview',
' tekken expert tips and trick',
' tekken expert gameplay',
' tekken expert common mistakes',
' tekken expert builds',
' tekken expert players',
' tekken expert noobs',
' tekken expert news',
' tekken expert tutorial',
' tekken pro guide',
' tekken pro tutorial',
' tekken pro strategy',
' tekken pro methods',
' tekken pro lessons',
' tekken pro techniques',
' tekken pro videos',
' tekken pro lessons',
' tekken pro tactics',
' tekken pro overview',
' tekken pro tips and trick',
' tekken pro gameplay',
' tekken pro common mistakes',
' tekken pro builds',
' tekken pro players',
' tekken pro noobs',
' tekken pro news',
' tekken pro tutorial',
'killer instinct beginner guide',
'killer instinct beginner tutorial',
'killer instinct beginner strategy',
'killer instinct beginner methods',
'killer instinct beginner lessons',
'killer instinct beginner techniques',
'killer instinct beginner videos',
'killer instinct beginner lessons',
'killer instinct beginner tactics',
'killer instinct beginner overview',
'killer instinct beginner tips and trick',
'killer instinct beginner gameplay',
'killer instinct beginner common mistakes',
'killer instinct beginner builds',
'killer instinct beginner players',
'killer instinct beginner noobs',
'killer instinct beginner news',
'killer instinct tutorial',
'killer instinct intermediate guide',
'killer instinct intermediate tutorial',
'killer instinct intermediate strategy',
'killer instinct intermediate methods',
'killer instinct intermediate lessons',
'killer instinct intermediate techniques',
'killer instinct intermediate videos',
'killer instinct intermediate lessons',
'killer instinct intermediate tactics',
'killer instinct intermediate overview',
'killer instinct intermediate tips and trick',
'killer instinct intermediate gameplay',
'killer instinct intermediate common mistakes',
'killer instinct intermediate builds',
'killer instinct intermediate players',
'killer instinct intermediate noobs',
'killer instinct intermediate news',
'killer instinct intermediate tutorial',
'killer instinct expert guide',
'killer instinct expert tutorial',
'killer instinct expert strategy',
'killer instinct expert methods',
'killer instinct expert lessons',
'killer instinct expert techniques',
'killer instinct expert videos',
'killer instinct expert lessons',
'killer instinct expert tactics',
'killer instinct expert overview',
'killer instinct expert tips and trick',
'killer instinct expert gameplay',
'killer instinct expert common mistakes',
'killer instinct expert builds',
'killer instinct expert players',
'killer instinct expert noobs',
'killer instinct expert news',
'killer instinct expert tutorial',
'killer instinct pro guide',
'killer instinct pro tutorial',
'killer instinct pro strategy',
'killer instinct pro methods',
'killer instinct pro lessons',
'killer instinct pro techniques',
'killer instinct pro videos',
'killer instinct pro lessons',
'killer instinct pro tactics',
'killer instinct pro overview',
'killer instinct pro tips and trick',
'killer instinct pro gameplay',
'killer instinct pro common mistakes',
'killer instinct pro builds',
'killer instinct pro players',
'killer instinct pro noobs',
'killer instinct pro news',
'killer instinct pro tutorial',
'doom beginner guide',
'doom beginner tutorial',
'doom beginner strategy',
'doom beginner methods',
'doom beginner lessons',
'doom beginner techniques',
'doom beginner videos',
'doom beginner lessons',
'doom beginner tactics',
'doom beginner overview',
'doom beginner tips and trick',
'doom beginner gameplay',
'doom beginner common mistakes',
'doom beginner builds',
'doom beginner players',
'doom beginner noobs',
'doom beginner news',
'doom tutorial',
'doom intermediate guide',
'doom intermediate tutorial',
'doom intermediate strategy',
'doom intermediate methods',
'doom intermediate lessons',
'doom intermediate techniques',
'doom intermediate videos',
'doom intermediate lessons',
'doom intermediate tactics',
'doom intermediate overview',
'doom intermediate tips and trick',
'doom intermediate gameplay',
'doom intermediate common mistakes',
'doom intermediate builds',
'doom intermediate players',
'doom intermediate noobs',
'doom intermediate news',
'doom intermediate tutorial',
'doom expert guide',
'doom expert tutorial',
'doom expert strategy',
'doom expert methods',
'doom expert lessons',
'doom expert techniques',
'doom expert videos',
'doom expert lessons',
'doom expert tactics',
'doom expert overview',
'doom expert tips and trick',
'doom expert gameplay',
'doom expert common mistakes',
'doom expert builds',
'doom expert players',
'doom expert noobs',
'doom expert news',
'doom expert tutorial',
'doom pro guide',
'doom pro tutorial',
'doom pro strategy',
'doom pro methods',
'doom pro lessons',
'doom pro techniques',
'doom pro videos',
'doom pro lessons',
'doom pro tactics',
'doom pro overview',
'doom pro tips and trick',
'doom pro gameplay',
'doom pro common mistakes',
'doom pro builds',
'doom pro players',
'doom pro noobs',
'doom pro news',
'doom pro tutorial',
'quake beginner guide',
'quake beginner tutorial',
'quake beginner strategy',
'quake beginner methods',
'quake beginner lessons',
'quake beginner techniques',
'quake beginner videos',
'quake beginner lessons',
'quake beginner tactics',
'quake beginner overview',
'quake beginner tips and trick',
'quake beginner gameplay',
'quake beginner common mistakes',
'quake beginner builds',
'quake beginner players',
'quake beginner noobs',
'quake beginner news',
'quake tutorial',
'quake intermediate guide',
'quake intermediate tutorial',
'quake intermediate strategy',
'quake intermediate methods',
'quake intermediate lessons',
'quake intermediate techniques',
'quake intermediate videos',
'quake intermediate lessons',
'quake intermediate tactics',
'quake intermediate overview',
'quake intermediate tips and trick',
'quake intermediate gameplay',
'quake intermediate common mistakes',
'quake intermediate builds',
'quake intermediate players',
'quake intermediate noobs',
'quake intermediate news',
'quake intermediate tutorial',
'quake expert guide',
'quake expert tutorial',
'quake expert strategy',
'quake expert methods',
'quake expert lessons',
'quake expert techniques',
'quake expert videos',
'quake expert lessons',
'quake expert tactics',
'quake expert overview',
'quake expert tips and trick',
'quake expert gameplay',
'quake expert common mistakes',
'quake expert builds',
'quake expert players',
'quake expert noobs',
'quake expert news',
'quake expert tutorial',
'quake pro guide',
'quake pro tutorial',
'quake pro strategy',
'quake pro methods',
'quake pro lessons',
'quake pro techniques',
'quake pro videos',
'quake pro lessons',
'quake pro tactics',
'quake pro overview',
'quake pro tips and trick',
'quake pro gameplay',
'quake pro common mistakes',
'quake pro builds',
'quake pro players',
'quake pro noobs',
'quake pro news',
'quake pro tutorial',
'counter strike beginner guide',
'counter strike beginner tutorial',
'counter strike beginner strategy',
'counter strike beginner methods',
'counter strike beginner lessons',
'counter strike beginner techniques',
'counter strike beginner videos',
'counter strike beginner lessons',
'counter strike beginner tactics',
'counter strike beginner overview',
'counter strike beginner tips and trick',
'counter strike beginner gameplay',
'counter strike beginner common mistakes',
'counter strike beginner builds',
'counter strike beginner players',
'counter strike beginner noobs',
'counter strike beginner news',
'counter strike tutorial',
'counter strike intermediate guide',
'counter strike intermediate tutorial',
'counter strike intermediate strategy',
'counter strike intermediate methods',
'counter strike intermediate lessons',
'counter strike intermediate techniques',
'counter strike intermediate videos',
'counter strike intermediate lessons',
'counter strike intermediate tactics',
'counter strike intermediate overview',
'counter strike intermediate tips and trick',
'counter strike intermediate gameplay',
'counter strike intermediate common mistakes',
'counter strike intermediate builds',
'counter strike intermediate players',
'counter strike intermediate noobs',
'counter strike intermediate news',
'counter strike intermediate tutorial',
'counter strike expert guide',
'counter strike expert tutorial',
'counter strike expert strategy',
'counter strike expert methods',
'counter strike expert lessons',
'counter strike expert techniques',
'counter strike expert videos',
'counter strike expert lessons',
'counter strike expert tactics',
'counter strike expert overview',
'counter strike expert tips and trick',
'counter strike expert gameplay',
'counter strike expert common mistakes',
'counter strike expert builds',
'counter strike expert players',
'counter strike expert noobs',
'counter strike expert news',
'counter strike expert tutorial',
'counter strike pro guide',
'counter strike pro tutorial',
'counter strike pro strategy',
'counter strike pro methods',
'counter strike pro lessons',
'counter strike pro techniques',
'counter strike pro videos',
'counter strike pro lessons',
'counter strike pro tactics',
'counter strike pro overview',
'counter strike pro tips and trick',
'counter strike pro gameplay',
'counter strike pro common mistakes',
'counter strike pro builds',
'counter strike pro players',
'counter strike pro noobs',
'counter strike pro news',
'counter strike pro tutorial',
'unreal tournement beginner guide',
'unreal tournement beginner tutorial',
'unreal tournement beginner strategy',
'unreal tournement beginner methods',
'unreal tournement beginner lessons',
'unreal tournement beginner techniques',
'unreal tournement beginner videos',
'unreal tournement beginner lessons',
'unreal tournement beginner tactics',
'unreal tournement beginner overview',
'unreal tournement beginner tips and trick',
'unreal tournement beginner gameplay',
'unreal tournement beginner common mistakes',
'unreal tournement beginner builds',
'unreal tournement beginner players',
'unreal tournement beginner noobs',
'unreal tournement beginner news',
'unreal tournement tutorial',
'unreal tournement intermediate guide',
'unreal tournement intermediate tutorial',
'unreal tournement intermediate strategy',
'unreal tournement intermediate methods',
'unreal tournement intermediate lessons',
'unreal tournement intermediate techniques',
'unreal tournement intermediate videos',
'unreal tournement intermediate lessons',
'unreal tournement intermediate tactics',
'unreal tournement intermediate overview',
'unreal tournement intermediate tips and trick',
'unreal tournement intermediate gameplay',
'unreal tournement intermediate common mistakes',
'unreal tournement intermediate builds',
'unreal tournement intermediate players',
'unreal tournement intermediate noobs',
'unreal tournement intermediate news',
'unreal tournement intermediate tutorial',
'unreal tournement expert guide',
'unreal tournement expert tutorial',
'unreal tournement expert strategy',
'unreal tournement expert methods',
'unreal tournement expert lessons',
'unreal tournement expert techniques',
'unreal tournement expert videos',
'unreal tournement expert lessons',
'unreal tournement expert tactics',
'unreal tournement expert overview',
'unreal tournement expert tips and trick',
'unreal tournement expert gameplay',
'unreal tournement expert common mistakes',
'unreal tournement expert builds',
'unreal tournement expert players',
'unreal tournement expert noobs',
'unreal tournement expert news',
'unreal tournement expert tutorial',
'unreal tournement pro guide',
'unreal tournement pro tutorial',
'unreal tournement pro strategy',
'unreal tournement pro methods',
'unreal tournement pro lessons',
'unreal tournement pro techniques',
'unreal tournement pro videos',
'unreal tournement pro lessons',
'unreal tournement pro tactics',
'unreal tournement pro overview',
'unreal tournement pro tips and trick',
'unreal tournement pro gameplay',
'unreal tournement pro common mistakes',
'unreal tournement pro builds',
'unreal tournement pro players',
'unreal tournement pro noobs',
'unreal tournement pro news',
'unreal tournement pro tutorial',
'halo beginner guide',
'halo beginner tutorial',
'halo beginner strategy',
'halo beginner methods',
'halo beginner lessons',
'halo beginner techniques',
'halo beginner videos',
'halo beginner lessons',
'halo beginner tactics',
'halo beginner overview',
'halo beginner tips and trick',
'halo beginner gameplay',
'halo beginner common mistakes',
'halo beginner builds',
'halo beginner players',
'halo beginner noobs',
'halo beginner news',
'halo tutorial',
'halo intermediate guide',
'halo intermediate tutorial',
'halo intermediate strategy',
'halo intermediate methods',
'halo intermediate lessons',
'halo intermediate techniques',
'halo intermediate videos',
'halo intermediate lessons',
'halo intermediate tactics',
'halo intermediate overview',
'halo intermediate tips and trick',
'halo intermediate gameplay',
'halo intermediate common mistakes',
'halo intermediate builds',
'halo intermediate players',
'halo intermediate noobs',
'halo intermediate news',
'halo intermediate tutorial',
'halo expert guide',
'halo expert tutorial',
'halo expert strategy',
'halo expert methods',
'halo expert lessons',
'halo expert techniques',
'halo expert videos',
'halo expert lessons',
'halo expert tactics',
'halo expert overview',
'halo expert tips and trick',
'halo expert gameplay',
'halo expert common mistakes',
'halo expert builds',
'halo expert players',
'halo expert noobs',
'halo expert news',
'halo expert tutorial',
'halo pro guide',
'halo pro tutorial',
'halo pro strategy',
'halo pro methods',
'halo pro lessons',
'halo pro techniques',
'halo pro videos',
'halo pro lessons',
'halo pro tactics',
'halo pro overview',
'halo pro tips and trick',
'halo pro gameplay',
'halo pro common mistakes',
'halo pro builds',
'halo pro players',
'halo pro noobs',
'halo pro news',
'halo pro tutorial',
'painkiller beginner guide',
'painkiller beginner tutorial',
'painkiller beginner strategy',
'painkiller beginner methods',
'painkiller beginner lessons',
'painkiller beginner techniques',
'painkiller beginner videos',
'painkiller beginner lessons',
'painkiller beginner tactics',
'painkiller beginner overview',
'painkiller beginner tips and trick',
'painkiller beginner gameplay',
'painkiller beginner common mistakes',
'painkiller beginner builds',
'painkiller beginner players',
'painkiller beginner noobs',
'painkiller beginner news',
'painkiller tutorial',
'painkiller intermediate guide',
'painkiller intermediate tutorial',
'painkiller intermediate strategy',
'painkiller intermediate methods',
'painkiller intermediate lessons',
'painkiller intermediate techniques',
'painkiller intermediate videos',
'painkiller intermediate lessons',
'painkiller intermediate tactics',
'painkiller intermediate overview',
'painkiller intermediate tips and trick',
'painkiller intermediate gameplay',
'painkiller intermediate common mistakes',
'painkiller intermediate builds',
'painkiller intermediate players',
'painkiller intermediate noobs',
'painkiller intermediate news',
'painkiller intermediate tutorial',
'painkiller expert guide',
'painkiller expert tutorial',
'painkiller expert strategy',
'painkiller expert methods',
'painkiller expert lessons',
'painkiller expert techniques',
'painkiller expert videos',
'painkiller expert lessons',
'painkiller expert tactics',
'painkiller expert overview',
'painkiller expert tips and trick',
'painkiller expert gameplay',
'painkiller expert common mistakes',
'painkiller expert builds',
'painkiller expert players',
'painkiller expert noobs',
'painkiller expert news',
'painkiller expert tutorial',
'painkiller pro guide',
'painkiller pro tutorial',
'painkiller pro strategy',
'painkiller pro methods',
'painkiller pro lessons',
'painkiller pro techniques',
'painkiller pro videos',
'painkiller pro lessons',
'painkiller pro tactics',
'painkiller pro overview',
'painkiller pro tips and trick',
'painkiller pro gameplay',
'painkiller pro common mistakes',
'painkiller pro builds',
'painkiller pro players',
'painkiller pro noobs',
'painkiller pro news',
'painkiller pro tutorial',
'halo reach beginner guide',
'halo reach beginner tutorial',
'halo reach beginner strategy',
'halo reach beginner methods',
'halo reach beginner lessons',
'halo reach beginner techniques',
'halo reach beginner videos',
'halo reach beginner lessons',
'halo reach beginner tactics',
'halo reach beginner overview',
'halo reach beginner tips and trick',
'halo reach beginner gameplay',
'halo reach beginner common mistakes',
'halo reach beginner builds',
'halo reach beginner players',
'halo reach beginner noobs',
'halo reach beginner news',
'halo reach tutorial',
'halo reach intermediate guide',
'halo reach intermediate tutorial',
'halo reach intermediate strategy',
'halo reach intermediate methods',
'halo reach intermediate lessons',
'halo reach intermediate techniques',
'halo reach intermediate videos',
'halo reach intermediate lessons',
'halo reach intermediate tactics',
'halo reach intermediate overview',
'halo reach intermediate tips and trick',
'halo reach intermediate gameplay',
'halo reach intermediate common mistakes',
'halo reach intermediate builds',
'halo reach intermediate players',
'halo reach intermediate noobs',
'halo reach intermediate news',
'halo reach intermediate tutorial',
'halo reach expert guide',
'halo reach expert tutorial',
'halo reach expert strategy',
'halo reach expert methods',
'halo reach expert lessons',
'halo reach expert techniques',
'halo reach expert videos',
'halo reach expert lessons',
'halo reach expert tactics',
'halo reach expert overview',
'halo reach expert tips and trick',
'halo reach expert gameplay',
'halo reach expert common mistakes',
'halo reach expert builds',
'halo reach expert players',
'halo reach expert noobs',
'halo reach expert news',
'halo reach expert tutorial',
'halo reach pro guide',
'halo reach pro tutorial',
'halo reach pro strategy',
'halo reach pro methods',
'halo reach pro lessons',
'halo reach pro techniques',
'halo reach pro videos',
'halo reach pro lessons',
'halo reach pro tactics',
'halo reach pro overview',
'halo reach pro tips and trick',
'halo reach pro gameplay',
'halo reach pro common mistakes',
'halo reach pro builds',
'halo reach pro players',
'halo reach pro noobs',
'halo reach pro news',
'halo reach pro tutorial',
'reach odst beginner guide',
'reach odst beginner tutorial',
'reach odst beginner strategy',
'reach odst beginner methods',
'reach odst beginner lessons',
'reach odst beginner techniques',
'reach odst beginner videos',
'reach odst beginner lessons',
'reach odst beginner tactics',
'reach odst beginner overview',
'reach odst beginner tips and trick',
'reach odst beginner gameplay',
'reach odst beginner common mistakes',
'reach odst beginner builds',
'reach odst beginner players',
'reach odst beginner noobs',
'reach odst beginner news',
'reach odst tutorial',
'reach odst intermediate guide',
'reach odst intermediate tutorial',
'reach odst intermediate strategy',
'reach odst intermediate methods',
'reach odst intermediate lessons',
'reach odst intermediate techniques',
'reach odst intermediate videos',
'reach odst intermediate lessons',
'reach odst intermediate tactics',
'reach odst intermediate overview',
'reach odst intermediate tips and trick',
'reach odst intermediate gameplay',
'reach odst intermediate common mistakes',
'reach odst intermediate builds',
'reach odst intermediate players',
'reach odst intermediate noobs',
'reach odst intermediate news',
'reach odst intermediate tutorial',
'reach odst expert guide',
'reach odst expert tutorial',
'reach odst expert strategy',
'reach odst expert methods',
'reach odst expert lessons',
'reach odst expert techniques',
'reach odst expert videos',
'reach odst expert lessons',
'reach odst expert tactics',
'reach odst expert overview',
'reach odst expert tips and trick',
'reach odst expert gameplay',
'reach odst expert common mistakes',
'reach odst expert builds',
'reach odst expert players',
'reach odst expert noobs',
'reach odst expert news',
'reach odst expert tutorial',
'reach odst pro guide',
'reach odst pro tutorial',
'reach odst pro strategy',
'reach odst pro methods',
'reach odst pro lessons',
'reach odst pro techniques',
'reach odst pro videos',
'reach odst pro lessons',
'reach odst pro tactics',
'reach odst pro overview',
'reach odst pro tips and trick',
'reach odst pro gameplay',
'reach odst pro common mistakes',
'reach odst pro builds',
'reach odst pro players',
'reach odst pro noobs',
'reach odst pro news',
'reach odst pro tutorial',
'halo 5 beginner guide',
'halo 5 beginner tutorial',
'halo 5 beginner strategy',
'halo 5 beginner methods',
'halo 5 beginner lessons',
'halo 5 beginner techniques',
'halo 5 beginner videos',
'halo 5 beginner lessons',
'halo 5 beginner tactics',
'halo 5 beginner overview',
'halo 5 beginner tips and trick',
'halo 5 beginner gameplay',
'halo 5 beginner common mistakes',
'halo 5 beginner builds',
'halo 5 beginner players',
'halo 5 beginner noobs',
'halo 5 beginner news',
'halo 5 tutorial',
'halo 5 intermediate guide',
'halo 5 intermediate tutorial',
'halo 5 intermediate strategy',
'halo 5 intermediate methods',
'halo 5 intermediate lessons',
'halo 5 intermediate techniques',
'halo 5 intermediate videos',
'halo 5 intermediate lessons',
'halo 5 intermediate tactics',
'halo 5 intermediate overview',
'halo 5 intermediate tips and trick',
'halo 5 intermediate gameplay',
'halo 5 intermediate common mistakes',
'halo 5 intermediate builds',
'halo 5 intermediate players',
'halo 5 intermediate noobs',
'halo 5 intermediate news',
'halo 5 intermediate tutorial',
'halo 5 expert guide',
'halo 5 expert tutorial',
'halo 5 expert strategy',
'halo 5 expert methods',
'halo 5 expert lessons',
'halo 5 expert techniques',
'halo 5 expert videos',
'halo 5 expert lessons',
'halo 5 expert tactics',
'halo 5 expert overview',
'halo 5 expert tips and trick',
'halo 5 expert gameplay',
'halo 5 expert common mistakes',
'halo 5 expert builds',
'halo 5 expert players',
'halo 5 expert noobs',
'halo 5 expert news',
'halo 5 expert tutorial',
'halo 5 pro guide',
'halo 5 pro tutorial',
'halo 5 pro strategy',
'halo 5 pro methods',
'halo 5 pro lessons',
'halo 5 pro techniques',
'halo 5 pro videos',
'halo 5 pro lessons',
'halo 5 pro tactics',
'halo 5 pro overview',
'halo 5 pro tips and trick',
'halo 5 pro gameplay',
'halo 5 pro common mistakes',
'halo 5 pro builds',
'halo 5 pro players',
'halo 5 pro noobs',
'halo 5 pro news',
'halo 5 pro tutorial',
'team fortess 2 beginner guide',
'team fortess 2 beginner tutorial',
'team fortess 2 beginner strategy',
'team fortess 2 beginner methods',
'team fortess 2 beginner lessons',
'team fortess 2 beginner techniques',
'team fortess 2 beginner videos',
'team fortess 2 beginner lessons',
'team fortess 2 beginner tactics',
'team fortess 2 beginner overview',
'team fortess 2 beginner tips and trick',
'team fortess 2 beginner gameplay',
'team fortess 2 beginner common mistakes',
'team fortess 2 beginner builds',
'team fortess 2 beginner players',
'team fortess 2 beginner noobs',
'team fortess 2 beginner news',
'team fortess 2 tutorial',
'team fortess 2 intermediate guide',
'team fortess 2 intermediate tutorial',
'team fortess 2 intermediate strategy',
'team fortess 2 intermediate methods',
'team fortess 2 intermediate lessons',
'team fortess 2 intermediate techniques',
'team fortess 2 intermediate videos',
'team fortess 2 intermediate lessons',
'team fortess 2 intermediate tactics',
'team fortess 2 intermediate overview',
'team fortess 2 intermediate tips and trick',
'team fortess 2 intermediate gameplay',
'team fortess 2 intermediate common mistakes',
'team fortess 2 intermediate builds',
'team fortess 2 intermediate players',
'team fortess 2 intermediate noobs',
'team fortess 2 intermediate news',
'team fortess 2 intermediate tutorial',
'team fortess 2 expert guide',
'team fortess 2 expert tutorial',
'team fortess 2 expert strategy',
'team fortess 2 expert methods',
'team fortess 2 expert lessons',
'team fortess 2 expert techniques',
'team fortess 2 expert videos',
'team fortess 2 expert lessons',
'team fortess 2 expert tactics',
'team fortess 2 expert overview',
'team fortess 2 expert tips and trick',
'team fortess 2 expert gameplay',
'team fortess 2 expert common mistakes',
'team fortess 2 expert builds',
'team fortess 2 expert players',
'team fortess 2 expert noobs',
'team fortess 2 expert news',
'team fortess 2 expert tutorial',
'team fortess 2 pro guide',
'team fortess 2 pro tutorial',
'team fortess 2 pro strategy',
'team fortess 2 pro methods',
'team fortess 2 pro lessons',
'team fortess 2 pro techniques',
'team fortess 2 pro videos',
'team fortess 2 pro lessons',
'team fortess 2 pro tactics',
'team fortess 2 pro overview',
'team fortess 2 pro tips and trick',
'team fortess 2 pro gameplay',
'team fortess 2 pro common mistakes',
'team fortess 2 pro builds',
'team fortess 2 pro players',
'team fortess 2 pro noobs',
'team fortess 2 pro news',
'team fortess 2 pro tutorial',
'alliance of valiant arms beginner guide',
'alliance of valiant arms beginner tutorial',
'alliance of valiant arms beginner strategy',
'alliance of valiant arms beginner methods',
'alliance of valiant arms beginner lessons',
'alliance of valiant arms beginner techniques',
'alliance of valiant arms beginner videos',
'alliance of valiant arms beginner lessons',
'alliance of valiant arms beginner tactics',
'alliance of valiant arms beginner overview',
'alliance of valiant arms beginner tips and trick',
'alliance of valiant arms beginner gameplay',
'alliance of valiant arms beginner common mistakes',
'alliance of valiant arms beginner builds',
'alliance of valiant arms beginner players',
'alliance of valiant arms beginner noobs',
'alliance of valiant arms beginner news',
'alliance of valiant arms tutorial',
'alliance of valiant arms intermediate guide',
'alliance of valiant arms intermediate tutorial',
'alliance of valiant arms intermediate strategy',
'alliance of valiant arms intermediate methods',
'alliance of valiant arms intermediate lessons',
'alliance of valiant arms intermediate techniques',
'alliance of valiant arms intermediate videos',
'alliance of valiant arms intermediate lessons',
'alliance of valiant arms intermediate tactics',
'alliance of valiant arms intermediate overview',
'alliance of valiant arms intermediate tips and trick',
'alliance of valiant arms intermediate gameplay',
'alliance of valiant arms intermediate common mistakes',
'alliance of valiant arms intermediate builds',
'alliance of valiant arms intermediate players',
'alliance of valiant arms intermediate noobs',
'alliance of valiant arms intermediate news',
'alliance of valiant arms intermediate tutorial',
'alliance of valiant arms expert guide',
'alliance of valiant arms expert tutorial',
'alliance of valiant arms expert strategy',
'alliance of valiant arms expert methods',
'alliance of valiant arms expert lessons',
'alliance of valiant arms expert techniques',
'alliance of valiant arms expert videos',
'alliance of valiant arms expert lessons',
'alliance of valiant arms expert tactics',
'alliance of valiant arms expert overview',
'alliance of valiant arms expert tips and trick',
'alliance of valiant arms expert gameplay',
'alliance of valiant arms expert common mistakes',
'alliance of valiant arms expert builds',
'alliance of valiant arms expert players',
'alliance of valiant arms expert noobs',
'alliance of valiant arms expert news',
'alliance of valiant arms expert tutorial',
'alliance of valiant arms pro guide',
'alliance of valiant arms pro tutorial',
'alliance of valiant arms pro strategy',
'alliance of valiant arms pro methods',
'alliance of valiant arms pro lessons',
'alliance of valiant arms pro techniques',
'alliance of valiant arms pro videos',
'alliance of valiant arms pro lessons',
'alliance of valiant arms pro tactics',
'alliance of valiant arms pro overview',
'alliance of valiant arms pro tips and trick',
'alliance of valiant arms pro gameplay',
'alliance of valiant arms pro common mistakes',
'alliance of valiant arms pro builds',
'alliance of valiant arms pro players',
'alliance of valiant arms pro noobs',
'alliance of valiant arms pro news',
'alliance of valiant arms pro tutorial',
'special forces II beginner guide',
'special forces II beginner tutorial',
'special forces II beginner strategy',
'special forces II beginner methods',
'special forces II beginner lessons',
'special forces II beginner techniques',
'special forces II beginner videos',
'special forces II beginner lessons',
'special forces II beginner tactics',
'special forces II beginner overview',
'special forces II beginner tips and trick',
'special forces II beginner gameplay',
'special forces II beginner common mistakes',
'special forces II beginner builds',
'special forces II beginner players',
'special forces II beginner noobs',
'special forces II beginner news',
'special forces II tutorial',
'special forces II intermediate guide',
'special forces II intermediate tutorial',
'special forces II intermediate strategy',
'special forces II intermediate methods',
'special forces II intermediate lessons',
'special forces II intermediate techniques',
'special forces II intermediate videos',
'special forces II intermediate lessons',
'special forces II intermediate tactics',
'special forces II intermediate overview',
'special forces II intermediate tips and trick',
'special forces II intermediate gameplay',
'special forces II intermediate common mistakes',
'special forces II intermediate builds',
'special forces II intermediate players',
'special forces II intermediate noobs',
'special forces II intermediate news',
'special forces II intermediate tutorial',
'special forces II expert guide',
'special forces II expert tutorial',
'special forces II expert strategy',
'special forces II expert methods',
'special forces II expert lessons',
'special forces II expert techniques',
'special forces II expert videos',
'special forces II expert lessons',
'special forces II expert tactics',
'special forces II expert overview',
'special forces II expert tips and trick',
'special forces II expert gameplay',
'special forces II expert common mistakes',
'special forces II expert builds',
'special forces II expert players',
'special forces II expert noobs',
'special forces II expert news',
'special forces II expert tutorial',
'special forces II pro guide',
'special forces II pro tutorial',
'special forces II pro strategy',
'special forces II pro methods',
'special forces II pro lessons',
'special forces II pro techniques',
'special forces II pro videos',
'special forces II pro lessons',
'special forces II pro tactics',
'special forces II pro overview',
'special forces II pro tips and trick',
'special forces II pro gameplay',
'special forces II pro common mistakes',
'special forces II pro builds',
'special forces II pro players',
'special forces II pro noobs',
'special forces II pro news',
'special forces II pro tutorial',
'starcraft II beginner guide',
'starcraft II beginner tutorial',
'starcraft II beginner strategy',
'starcraft II beginner methods',
'starcraft II beginner lessons',
'starcraft II beginner techniques',
'starcraft II beginner videos',
'starcraft II beginner lessons',
'starcraft II beginner tactics',
'starcraft II beginner overview',
'starcraft II beginner tips and trick',
'starcraft II beginner gameplay',
'starcraft II beginner common mistakes',
'starcraft II beginner builds',
'starcraft II beginner players',
'starcraft II beginner noobs',
'starcraft II beginner news',
'starcraft II tutorial',
'starcraft II intermediate guide',
'starcraft II intermediate tutorial',
'starcraft II intermediate strategy',
'starcraft II intermediate methods',
'starcraft II intermediate lessons',
'starcraft II intermediate techniques',
'starcraft II intermediate videos',
'starcraft II intermediate lessons',
'starcraft II intermediate tactics',
'starcraft II intermediate overview',
'starcraft II intermediate tips and trick',
'starcraft II intermediate gameplay',
'starcraft II intermediate common mistakes',
'starcraft II intermediate builds',
'starcraft II intermediate players',
'starcraft II intermediate noobs',
'starcraft II intermediate news',
'starcraft II intermediate tutorial',
'starcraft II expert guide',
'starcraft II expert tutorial',
'starcraft II expert strategy',
'starcraft II expert methods',
'starcraft II expert lessons',
'starcraft II expert techniques',
'starcraft II expert videos',
'starcraft II expert lessons',
'starcraft II expert tactics',
'starcraft II expert overview',
'starcraft II expert tips and trick',
'starcraft II expert gameplay',
'starcraft II expert common mistakes',
'starcraft II expert builds',
'starcraft II expert players',
'starcraft II expert noobs',
'starcraft II expert news',
'starcraft II expert tutorial',
'starcraft II pro guide',
'starcraft II pro tutorial',
'starcraft II pro strategy',
'starcraft II pro methods',
'starcraft II pro lessons',
'starcraft II pro techniques',
'starcraft II pro videos',
'starcraft II pro lessons',
'starcraft II pro tactics',
'starcraft II pro overview',
'starcraft II pro tips and trick',
'starcraft II pro gameplay',
'starcraft II pro common mistakes',
'starcraft II pro builds',
'starcraft II pro players',
'starcraft II pro noobs',
'starcraft II pro news',
'starcraft II pro tutorial',
'FIFA 2017 beginner guide',
'FIFA 2017 beginner tutorial',
'FIFA 2017 beginner strategy',
'FIFA 2017 beginner methods',
'FIFA 2017 beginner lessons',
'FIFA 2017 beginner techniques',
'FIFA 2017 beginner videos',
'FIFA 2017 beginner lessons',
'FIFA 2017 beginner tactics',
'FIFA 2017 beginner overview',
'FIFA 2017 beginner tips and trick',
'FIFA 2017 beginner gameplay',
'FIFA 2017 beginner common mistakes',
'FIFA 2017 beginner builds',
'FIFA 2017 beginner players',
'FIFA 2017 beginner noobs',
'FIFA 2017 beginner news',
'FIFA 2017 tutorial',
'FIFA 2017 intermediate guide',
'FIFA 2017 intermediate tutorial',
'FIFA 2017 intermediate strategy',
'FIFA 2017 intermediate methods',
'FIFA 2017 intermediate lessons',
'FIFA 2017 intermediate techniques',
'FIFA 2017 intermediate videos',
'FIFA 2017 intermediate lessons',
'FIFA 2017 intermediate tactics',
'FIFA 2017 intermediate overview',
'FIFA 2017 intermediate tips and trick',
'FIFA 2017 intermediate gameplay',
'FIFA 2017 intermediate common mistakes',
'FIFA 2017 intermediate builds',
'FIFA 2017 intermediate players',
'FIFA 2017 intermediate noobs',
'FIFA 2017 intermediate news',
'FIFA 2017 intermediate tutorial',
'FIFA 2017 expert guide',
'FIFA 2017 expert tutorial',
'FIFA 2017 expert strategy',
'FIFA 2017 expert methods',
'FIFA 2017 expert lessons',
'FIFA 2017 expert techniques',
'FIFA 2017 expert videos',
'FIFA 2017 expert lessons',
'FIFA 2017 expert tactics',
'FIFA 2017 expert overview',
'FIFA 2017 expert tips and trick',
'FIFA 2017 expert gameplay',
'FIFA 2017 expert common mistakes',
'FIFA 2017 expert builds',
'FIFA 2017 expert players',
'FIFA 2017 expert noobs',
'FIFA 2017 expert news',
'FIFA 2017 expert tutorial',
'FIFA 2017 pro guide',
'FIFA 2017 pro tutorial',
'FIFA 2017 pro strategy',
'FIFA 2017 pro methods',
'FIFA 2017 pro lessons',
'FIFA 2017 pro techniques',
'FIFA 2017 pro videos',
'FIFA 2017 pro lessons',
'FIFA 2017 pro tactics',
'FIFA 2017 pro overview',
'FIFA 2017 pro tips and trick',
'FIFA 2017 pro gameplay',
'FIFA 2017 pro common mistakes',
'FIFA 2017 pro builds',
'FIFA 2017 pro players',
'FIFA 2017 pro noobs',
'FIFA 2017 pro news',
'FIFA 2017 pro tutorial',
'madden 2017 beginner guide',
'madden 2017 beginner tutorial',
'madden 2017 beginner strategy',
'madden 2017 beginner methods',
'madden 2017 beginner lessons',
'madden 2017 beginner techniques',
'madden 2017 beginner videos',
'madden 2017 beginner lessons',
'madden 2017 beginner tactics',
'madden 2017 beginner overview',
'madden 2017 beginner tips and trick',
'madden 2017 beginner gameplay',
'madden 2017 beginner common mistakes',
'madden 2017 beginner builds',
'madden 2017 beginner players',
'madden 2017 beginner noobs',
'madden 2017 beginner news',
'madden 2017 tutorial',
'madden 2017 intermediate guide',
'madden 2017 intermediate tutorial',
'madden 2017 intermediate strategy',
'madden 2017 intermediate methods',
'madden 2017 intermediate lessons',
'madden 2017 intermediate techniques',
'madden 2017 intermediate videos',
'madden 2017 intermediate lessons',
'madden 2017 intermediate tactics',
'madden 2017 intermediate overview',
'madden 2017 intermediate tips and trick',
'madden 2017 intermediate gameplay',
'madden 2017 intermediate common mistakes',
'madden 2017 intermediate builds',
'madden 2017 intermediate players',
'madden 2017 intermediate noobs',
'madden 2017 intermediate news',
'madden 2017 intermediate tutorial',
'madden 2017 expert guide',
'madden 2017 expert tutorial',
'madden 2017 expert strategy',
'madden 2017 expert methods',
'madden 2017 expert lessons',
'madden 2017 expert techniques',
'madden 2017 expert videos',
'madden 2017 expert lessons',
'madden 2017 expert tactics',
'madden 2017 expert overview',
'madden 2017 expert tips and trick',
'madden 2017 expert gameplay',
'madden 2017 expert common mistakes',
'madden 2017 expert builds',
'madden 2017 expert players',
'madden 2017 expert noobs',
'madden 2017 expert news',
'madden 2017 expert tutorial',
'madden 2017 pro guide',
'madden 2017 pro tutorial',
'madden 2017 pro strategy',
'madden 2017 pro methods',
'madden 2017 pro lessons',
'madden 2017 pro techniques',
'madden 2017 pro videos',
'madden 2017 pro lessons',
'madden 2017 pro tactics',
'madden 2017 pro overview',
'madden 2017 pro tips and trick',
'madden 2017 pro gameplay',
'madden 2017 pro common mistakes',
'madden 2017 pro builds',
'madden 2017 pro players',
'madden 2017 pro noobs',
'madden 2017 pro news',
'madden 2017 pro tutorial',
'NBA 2k beginner guide',
'NBA 2k beginner tutorial',
'NBA 2k beginner strategy',
'NBA 2k beginner methods',
'NBA 2k beginner lessons',
'NBA 2k beginner techniques',
'NBA 2k beginner videos',
'NBA 2k beginner lessons',
'NBA 2k beginner tactics',
'NBA 2k beginner overview',
'NBA 2k beginner tips and trick',
'NBA 2k beginner gameplay',
'NBA 2k beginner common mistakes',
'NBA 2k beginner builds',
'NBA 2k beginner players',
'NBA 2k beginner noobs',
'NBA 2k beginner news',
'NBA 2k tutorial',
'NBA 2k intermediate guide',
'NBA 2k intermediate tutorial',
'NBA 2k intermediate strategy',
'NBA 2k intermediate methods',
'NBA 2k intermediate lessons',
'NBA 2k intermediate techniques',
'NBA 2k intermediate videos',
'NBA 2k intermediate lessons',
'NBA 2k intermediate tactics',
'NBA 2k intermediate overview',
'NBA 2k intermediate tips and trick',
'NBA 2k intermediate gameplay',
'NBA 2k intermediate common mistakes',
'NBA 2k intermediate builds',
'NBA 2k intermediate players',
'NBA 2k intermediate noobs',
'NBA 2k intermediate news',
'NBA 2k intermediate tutorial',
'NBA 2k expert guide',
'NBA 2k expert tutorial',
'NBA 2k expert strategy',
'NBA 2k expert methods',
'NBA 2k expert lessons',
'NBA 2k expert techniques',
'NBA 2k expert videos',
'NBA 2k expert lessons',
'NBA 2k expert tactics',
'NBA 2k expert overview',
'NBA 2k expert tips and trick',
'NBA 2k expert gameplay',
'NBA 2k expert common mistakes',
'NBA 2k expert builds',
'NBA 2k expert players',
'NBA 2k expert noobs',
'NBA 2k expert news',
'NBA 2k expert tutorial',
'NBA 2k pro guide',
'NBA 2k pro tutorial',
'NBA 2k pro strategy',
'NBA 2k pro methods',
'NBA 2k pro lessons',
'NBA 2k pro techniques',
'NBA 2k pro videos',
'NBA 2k pro lessons',
'NBA 2k pro tactics',
'NBA 2k pro overview',
'NBA 2k pro tips and trick',
'NBA 2k pro gameplay',
'NBA 2k pro common mistakes',
'NBA 2k pro builds',
'NBA 2k pro players',
'NBA 2k pro noobs',
'NBA 2k pro news',
'NBA 2k pro tutorial',
'rocket league beginner guide',
'rocket league beginner tutorial',
'rocket league beginner strategy',
'rocket league beginner methods',
'rocket league beginner lessons',
'rocket league beginner techniques',
'rocket league beginner videos',
'rocket league beginner lessons',
'rocket league beginner tactics',
'rocket league beginner overview',
'rocket league beginner tips and trick',
'rocket league beginner gameplay',
'rocket league beginner common mistakes',
'rocket league beginner builds',
'rocket league beginner players',
'rocket league beginner noobs',
'rocket league beginner news',
'rocket league tutorial',
'rocket league intermediate guide',
'rocket league intermediate tutorial',
'rocket league intermediate strategy',
'rocket league intermediate methods',
'rocket league intermediate lessons',
'rocket league intermediate techniques',
'rocket league intermediate videos',
'rocket league intermediate lessons',
'rocket league intermediate tactics',
'rocket league intermediate overview',
'rocket league intermediate tips and trick',
'rocket league intermediate gameplay',
'rocket league intermediate common mistakes',
'rocket league intermediate builds',
'rocket league intermediate players',
'rocket league intermediate noobs',
'rocket league intermediate news',
'rocket league intermediate tutorial',
'rocket league expert guide',
'rocket league expert tutorial',
'rocket league expert strategy',
'rocket league expert methods',
'rocket league expert lessons',
'rocket league expert techniques',
'rocket league expert videos',
'rocket league expert lessons',
'rocket league expert tactics',
'rocket league expert overview',
'rocket league expert tips and trick',
'rocket league expert gameplay',
'rocket league expert common mistakes',
'rocket league expert builds',
'rocket league expert players',
'rocket league expert noobs',
'rocket league expert news',
'rocket league expert tutorial',
'rocket league pro guide',
'rocket league pro tutorial',
'rocket league pro strategy',
'rocket league pro methods',
'rocket league pro lessons',
'rocket league pro techniques',
'rocket league pro videos',
'rocket league pro lessons',
'rocket league pro tactics',
'rocket league pro overview',
'rocket league pro tips and trick',
'rocket league pro gameplay',
'rocket league pro common mistakes',
'rocket league pro builds',
'rocket league pro players',
'rocket league pro noobs',
'rocket league pro news',
'rocket league pro tutorial',
'Dota 2 beginner guide',
'Dota 2 beginner tutorial',
'Dota 2 beginner strategy',
'Dota 2 beginner methods',
'Dota 2 beginner lessons',
'Dota 2 beginner techniques',
'Dota 2 beginner videos',
'Dota 2 beginner lessons',
'Dota 2 beginner tactics',
'Dota 2 beginner overview',
'Dota 2 beginner tips and trick',
'Dota 2 beginner gameplay',
'Dota 2 beginner common mistakes',
'Dota 2 beginner builds',
'Dota 2 beginner players',
'Dota 2 beginner noobs',
'Dota 2 beginner news',
'Dota 2 tutorial',
'Dota 2 intermediate guide',
'Dota 2 intermediate tutorial',
'Dota 2 intermediate strategy',
'Dota 2 intermediate methods',
'Dota 2 intermediate lessons',
'Dota 2 intermediate techniques',
'Dota 2 intermediate videos',
'Dota 2 intermediate lessons',
'Dota 2 intermediate tactics',
'Dota 2 intermediate overview',
'Dota 2 intermediate tips and trick',
'Dota 2 intermediate gameplay',
'Dota 2 intermediate common mistakes',
'Dota 2 intermediate builds',
'Dota 2 intermediate players',
'Dota 2 intermediate noobs',
'Dota 2 intermediate news',
'Dota 2 intermediate tutorial',
'Dota 2 expert guide',
'Dota 2 expert tutorial',
'Dota 2 expert strategy',
'Dota 2 expert methods',
'Dota 2 expert lessons',
'Dota 2 expert techniques',
'Dota 2 expert videos',
'Dota 2 expert lessons',
'Dota 2 expert tactics',
'Dota 2 expert overview',
'Dota 2 expert tips and trick',
'Dota 2 expert gameplay',
'Dota 2 expert common mistakes',
'Dota 2 expert builds',
'Dota 2 expert players',
'Dota 2 expert noobs',
'Dota 2 expert news',
'Dota 2 expert tutorial',
'Dota 2 pro guide',
'Dota 2 pro tutorial',
'Dota 2 pro strategy',
'Dota 2 pro methods',
'Dota 2 pro lessons',
'Dota 2 pro techniques',
'Dota 2 pro videos',
'Dota 2 pro lessons',
'Dota 2 pro tactics',
'Dota 2 pro overview',
'Dota 2 pro tips and trick',
'Dota 2 pro gameplay',
'Dota 2 pro common mistakes',
'Dota 2 pro builds',
'Dota 2 pro players',
'Dota 2 pro noobs',
'Dota 2 pro news',
'Dota 2 pro tutorial',


    ]

if __name__ == '__main__':
    base_youtube_code.os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'
    client = base_youtube_code.get_authenticated_service()
    # NEED TO PASS IN CLIENT INTO FUNCTIONS!

    # get a list of channel IDs related to keywork

    for keyword in kw:
        print('keyword is: '+ keyword)
        channelId_list = keyword_search.run_keyword_search(client,keyword)

        # if channelId exist in database:
        # do not run

        for channelId in channelId_list:
            connection = sqlite3.connect('core.db')
            c = connection.cursor()
            creatorIdTuple = (channelId,)

            c.execute("""
                SELECT * FROM video
                WHERE creatorID = ?
                """, creatorIdTuple)

            existing_videoCount = c.fetchall()

            connection.commit()
            connection.close()

            # if there is a result in DB, have videos from creator saved
            if len(existing_videoCount) > 0:
                print('already discovered')
            # if results == 0, no videos saved from creator, just discovered a new creator
            else:
                videoId_list = get_channel_videos.run_get_channel_videos(client, channelId)
                for videoId in videoId_list:
                    video_statistics.run_video_statistics(client, videoId)
                print('new creator discovered')
                get_channel_stats.runStats(channelId)