import base_youtube_code
import keyword_search
import get_channel_videos
import video_statistics
import get_channel_stats
import sqlite3

# run file to start function flow

# IMPORTANT IMPORTANT IMPORTANT IMPORTANT

#########################################################
#########################################################
#########################################################
####REMEMBER TO RECORD THE REFERENCE NUMBERS INSIDE SCRATCH PAD#####################
#########################################################


kw = keywords = [

'elder scrolls online beginner guide',
'elder scrolls online beginner tutorial',
'elder scrolls online beginner strategy',
'elder scrolls online beginner methods',
'elder scrolls online beginner lessons',
'elder scrolls online beginner techniques',
'elder scrolls online beginner videos',
'elder scrolls online beginner lessons',
'elder scrolls online beginner tactics',
'elder scrolls online beginner overview',
'elder scrolls online beginner tips and trick',
'elder scrolls online beginner gameplay',
'elder scrolls online beginner common mistakes',
'elder scrolls online beginner builds',
'elder scrolls online beginner players',
'elder scrolls online beginner noobs',
'elder scrolls online beginner news',
'elder scrolls online tutorial',
'elder scrolls online intermediate guide',
'elder scrolls online intermediate tutorial',
'elder scrolls online intermediate strategy',
'elder scrolls online intermediate methods',
'elder scrolls online intermediate lessons',
'elder scrolls online intermediate techniques',
'elder scrolls online intermediate videos',
'elder scrolls online intermediate lessons',
'elder scrolls online intermediate tactics',
'elder scrolls online intermediate overview',
'elder scrolls online intermediate tips and trick',
'elder scrolls online intermediate gameplay',
'elder scrolls online intermediate common mistakes',
'elder scrolls online intermediate builds',
'elder scrolls online intermediate players',
'elder scrolls online intermediate noobs',
'elder scrolls online intermediate news',
'elder scrolls online intermediate tutorial',
'elder scrolls online expert guide',
'elder scrolls online expert tutorial',
'elder scrolls online expert strategy',
'elder scrolls online expert methods',
'elder scrolls online expert lessons',
'elder scrolls online expert techniques',
'elder scrolls online expert videos',
'elder scrolls online expert lessons',
'elder scrolls online expert tactics',
'elder scrolls online expert overview',
'elder scrolls online expert tips and trick',
'elder scrolls online expert gameplay',
'elder scrolls online expert common mistakes',
'elder scrolls online expert builds',
'elder scrolls online expert players',
'elder scrolls online expert noobs',
'elder scrolls online expert news',
'elder scrolls online expert tutorial',
'elder scrolls online pro guide',
'elder scrolls online pro tutorial',
'elder scrolls online pro strategy',
'elder scrolls online pro methods',
'elder scrolls online pro lessons',
'elder scrolls online pro techniques',
'elder scrolls online pro videos',
'elder scrolls online pro lessons',
'elder scrolls online pro tactics',
'elder scrolls online pro overview',
'elder scrolls online pro tips and trick',
'elder scrolls online pro gameplay',
'elder scrolls online pro common mistakes',
'elder scrolls online pro builds',
'elder scrolls online pro players',
'elder scrolls online pro noobs',
'elder scrolls online pro news',
'elder scrolls online pro tutorial',
'final fantasy xiv beginner guide',
'final fantasy xiv beginner tutorial',
'final fantasy xiv beginner strategy',
'final fantasy xiv beginner methods',
'final fantasy xiv beginner lessons',
'final fantasy xiv beginner techniques',
'final fantasy xiv beginner videos',
'final fantasy xiv beginner lessons',
'final fantasy xiv beginner tactics',
'final fantasy xiv beginner overview',
'final fantasy xiv beginner tips and trick',
'final fantasy xiv beginner gameplay',
'final fantasy xiv beginner common mistakes',
'final fantasy xiv beginner builds',
'final fantasy xiv beginner players',
'final fantasy xiv beginner noobs',
'final fantasy xiv beginner news',
'final fantasy xiv tutorial',
'final fantasy xiv intermediate guide',
'final fantasy xiv intermediate tutorial',
'final fantasy xiv intermediate strategy',
'final fantasy xiv intermediate methods',
'final fantasy xiv intermediate lessons',
'final fantasy xiv intermediate techniques',
'final fantasy xiv intermediate videos',
'final fantasy xiv intermediate lessons',
'final fantasy xiv intermediate tactics',
'final fantasy xiv intermediate overview',
'final fantasy xiv intermediate tips and trick',
'final fantasy xiv intermediate gameplay',
'final fantasy xiv intermediate common mistakes',
'final fantasy xiv intermediate builds',
'final fantasy xiv intermediate players',
'final fantasy xiv intermediate noobs',
'final fantasy xiv intermediate news',
'final fantasy xiv intermediate tutorial',
'final fantasy xiv expert guide',
'final fantasy xiv expert tutorial',
'final fantasy xiv expert strategy',
'final fantasy xiv expert methods',
'final fantasy xiv expert lessons',
'final fantasy xiv expert techniques',
'final fantasy xiv expert videos',
'final fantasy xiv expert lessons',
'final fantasy xiv expert tactics',
'final fantasy xiv expert overview',
'final fantasy xiv expert tips and trick',
'final fantasy xiv expert gameplay',
'final fantasy xiv expert common mistakes',
'final fantasy xiv expert builds',
'final fantasy xiv expert players',
'final fantasy xiv expert noobs',
'final fantasy xiv expert news',
'final fantasy xiv expert tutorial',
'final fantasy xiv pro guide',
'final fantasy xiv pro tutorial',
'final fantasy xiv pro strategy',
'final fantasy xiv pro methods',
'final fantasy xiv pro lessons',
'final fantasy xiv pro techniques',
'final fantasy xiv pro videos',
'final fantasy xiv pro lessons',
'final fantasy xiv pro tactics',
'final fantasy xiv pro overview',
'final fantasy xiv pro tips and trick',
'final fantasy xiv pro gameplay',
'final fantasy xiv pro common mistakes',
'final fantasy xiv pro builds',
'final fantasy xiv pro players',
'final fantasy xiv pro noobs',
'final fantasy xiv pro news',
'final fantasy xiv pro tutorial',
'star wars the old republic beginner guide',
'star wars the old republic beginner tutorial',
'star wars the old republic beginner strategy',
'star wars the old republic beginner methods',
'star wars the old republic beginner lessons',
'star wars the old republic beginner techniques',
'star wars the old republic beginner videos',
'star wars the old republic beginner lessons',
'star wars the old republic beginner tactics',
'star wars the old republic beginner overview',
'star wars the old republic beginner tips and trick',
'star wars the old republic beginner gameplay',
'star wars the old republic beginner common mistakes',
'star wars the old republic beginner builds',
'star wars the old republic beginner players',
'star wars the old republic beginner noobs',
'star wars the old republic beginner news',
'star wars the old republic tutorial',
'star wars the old republic intermediate guide',
'star wars the old republic intermediate tutorial',
'star wars the old republic intermediate strategy',
'star wars the old republic intermediate methods',
'star wars the old republic intermediate lessons',
'star wars the old republic intermediate techniques',
'star wars the old republic intermediate videos',
'star wars the old republic intermediate lessons',
'star wars the old republic intermediate tactics',
'star wars the old republic intermediate overview',
'star wars the old republic intermediate tips and trick',
'star wars the old republic intermediate gameplay',
'star wars the old republic intermediate common mistakes',
'star wars the old republic intermediate builds',
'star wars the old republic intermediate players',
'star wars the old republic intermediate noobs',
'star wars the old republic intermediate news',
'star wars the old republic intermediate tutorial',
'star wars the old republic expert guide',
'star wars the old republic expert tutorial',
'star wars the old republic expert strategy',
'star wars the old republic expert methods',
'star wars the old republic expert lessons',
'star wars the old republic expert techniques',
'star wars the old republic expert videos',
'star wars the old republic expert lessons',
'star wars the old republic expert tactics',
'star wars the old republic expert overview',
'star wars the old republic expert tips and trick',
'star wars the old republic expert gameplay',
'star wars the old republic expert common mistakes',
'star wars the old republic expert builds',
'star wars the old republic expert players',
'star wars the old republic expert noobs',
'star wars the old republic expert news',
'star wars the old republic expert tutorial',
'star wars the old republic pro guide',
'star wars the old republic pro tutorial',
'star wars the old republic pro strategy',
'star wars the old republic pro methods',
'star wars the old republic pro lessons',
'star wars the old republic pro techniques',
'star wars the old republic pro videos',
'star wars the old republic pro lessons',
'star wars the old republic pro tactics',
'star wars the old republic pro overview',
'star wars the old republic pro tips and trick',
'star wars the old republic pro gameplay',
'star wars the old republic pro common mistakes',
'star wars the old republic pro builds',
'star wars the old republic pro players',
'star wars the old republic pro noobs',
'star wars the old republic pro news',
'star wars the old republic pro tutorial',
'eve online beginner guide',
'eve online beginner tutorial',
'eve online beginner strategy',
'eve online beginner methods',
'eve online beginner lessons',
'eve online beginner techniques',
'eve online beginner videos',
'eve online beginner lessons',
'eve online beginner tactics',
'eve online beginner overview',
'eve online beginner tips and trick',
'eve online beginner gameplay',
'eve online beginner common mistakes',
'eve online beginner builds',
'eve online beginner players',
'eve online beginner noobs',
'eve online beginner news',
'eve online tutorial',
'eve online intermediate guide',
'eve online intermediate tutorial',
'eve online intermediate strategy',
'eve online intermediate methods',
'eve online intermediate lessons',
'eve online intermediate techniques',
'eve online intermediate videos',
'eve online intermediate lessons',
'eve online intermediate tactics',
'eve online intermediate overview',
'eve online intermediate tips and trick',
'eve online intermediate gameplay',
'eve online intermediate common mistakes',
'eve online intermediate builds',
'eve online intermediate players',
'eve online intermediate noobs',
'eve online intermediate news',
'eve online intermediate tutorial',
'eve online expert guide',
'eve online expert tutorial',
'eve online expert strategy',
'eve online expert methods',
'eve online expert lessons',
'eve online expert techniques',
'eve online expert videos',
'eve online expert lessons',
'eve online expert tactics',
'eve online expert overview',
'eve online expert tips and trick',
'eve online expert gameplay',
'eve online expert common mistakes',
'eve online expert builds',
'eve online expert players',
'eve online expert noobs',
'eve online expert news',
'eve online expert tutorial',
'eve online pro guide',
'eve online pro tutorial',
'eve online pro strategy',
'eve online pro methods',
'eve online pro lessons',
'eve online pro techniques',
'eve online pro videos',
'eve online pro lessons',
'eve online pro tactics',
'eve online pro overview',
'eve online pro tips and trick',
'eve online pro gameplay',
'eve online pro common mistakes',
'eve online pro builds',
'eve online pro players',
'eve online pro noobs',
'eve online pro news',
'eve online pro tutorial',
'archeage beginner guide',
'archeage beginner tutorial',
'archeage beginner strategy',
'archeage beginner methods',
'archeage beginner lessons',
'archeage beginner techniques',
'archeage beginner videos',
'archeage beginner lessons',
'archeage beginner tactics',
'archeage beginner overview',
'archeage beginner tips and trick',
'archeage beginner gameplay',
'archeage beginner common mistakes',
'archeage beginner builds',
'archeage beginner players',
'archeage beginner noobs',
'archeage beginner news',
'archeage tutorial',
'archeage intermediate guide',
'archeage intermediate tutorial',
'archeage intermediate strategy',
'archeage intermediate methods',
'archeage intermediate lessons',
'archeage intermediate techniques',
'archeage intermediate videos',
'archeage intermediate lessons',
'archeage intermediate tactics',
'archeage intermediate overview',
'archeage intermediate tips and trick',
'archeage intermediate gameplay',
'archeage intermediate common mistakes',
'archeage intermediate builds',
'archeage intermediate players',
'archeage intermediate noobs',
'archeage intermediate news',
'archeage intermediate tutorial',
'archeage expert guide',
'archeage expert tutorial',
'archeage expert strategy',
'archeage expert methods',
'archeage expert lessons',
'archeage expert techniques',
'archeage expert videos',
'archeage expert lessons',
'archeage expert tactics',
'archeage expert overview',
'archeage expert tips and trick',
'archeage expert gameplay',
'archeage expert common mistakes',
'archeage expert builds',
'archeage expert players',
'archeage expert noobs',
'archeage expert news',
'archeage expert tutorial',
'archeage pro guide',
'archeage pro tutorial',
'archeage pro strategy',
'archeage pro methods',
'archeage pro lessons',
'archeage pro techniques',
'archeage pro videos',
'archeage pro lessons',
'archeage pro tactics',
'archeage pro overview',
'archeage pro tips and trick',
'archeage pro gameplay',
'archeage pro common mistakes',
'archeage pro builds',
'archeage pro players',
'archeage pro noobs',
'archeage pro news',
'archeage pro tutorial',
'tera rising beginner guide',
'tera rising beginner tutorial',
'tera rising beginner strategy',
'tera rising beginner methods',
'tera rising beginner lessons',
'tera rising beginner techniques',
'tera rising beginner videos',
'tera rising beginner lessons',
'tera rising beginner tactics',
'tera rising beginner overview',
'tera rising beginner tips and trick',
'tera rising beginner gameplay',
'tera rising beginner common mistakes',
'tera rising beginner builds',
'tera rising beginner players',
'tera rising beginner noobs',
'tera rising beginner news',
'tera rising tutorial',
'tera rising intermediate guide',
'tera rising intermediate tutorial',
'tera rising intermediate strategy',
'tera rising intermediate methods',
'tera rising intermediate lessons',
'tera rising intermediate techniques',
'tera rising intermediate videos',
'tera rising intermediate lessons',
'tera rising intermediate tactics',
'tera rising intermediate overview',
'tera rising intermediate tips and trick',
'tera rising intermediate gameplay',
'tera rising intermediate common mistakes',
'tera rising intermediate builds',
'tera rising intermediate players',
'tera rising intermediate noobs',
'tera rising intermediate news',
'tera rising intermediate tutorial',
'tera rising expert guide',
'tera rising expert tutorial',
'tera rising expert strategy',
'tera rising expert methods',
'tera rising expert lessons',
'tera rising expert techniques',
'tera rising expert videos',
'tera rising expert lessons',
'tera rising expert tactics',
'tera rising expert overview',
'tera rising expert tips and trick',
'tera rising expert gameplay',
'tera rising expert common mistakes',
'tera rising expert builds',
'tera rising expert players',
'tera rising expert noobs',
'tera rising expert news',
'tera rising expert tutorial',
'tera rising pro guide',
'tera rising pro tutorial',
'tera rising pro strategy',
'tera rising pro methods',
'tera rising pro lessons',
'tera rising pro techniques',
'tera rising pro videos',
'tera rising pro lessons',
'tera rising pro tactics',
'tera rising pro overview',
'tera rising pro tips and trick',
'tera rising pro gameplay',
'tera rising pro common mistakes',
'tera rising pro builds',
'tera rising pro players',
'tera rising pro noobs',
'tera rising pro news',
'tera rising pro tutorial',
'guild wars 2 beginner guide',
'guild wars 2 beginner tutorial',
'guild wars 2 beginner strategy',
'guild wars 2 beginner methods',
'guild wars 2 beginner lessons',
'guild wars 2 beginner techniques',
'guild wars 2 beginner videos',
'guild wars 2 beginner lessons',
'guild wars 2 beginner tactics',
'guild wars 2 beginner overview',
'guild wars 2 beginner tips and trick',
'guild wars 2 beginner gameplay',
'guild wars 2 beginner common mistakes',
'guild wars 2 beginner builds',
'guild wars 2 beginner players',
'guild wars 2 beginner noobs',
'guild wars 2 beginner news',
'guild wars 2 tutorial',
'guild wars 2 intermediate guide',
'guild wars 2 intermediate tutorial',
'guild wars 2 intermediate strategy',
'guild wars 2 intermediate methods',
'guild wars 2 intermediate lessons',
'guild wars 2 intermediate techniques',
'guild wars 2 intermediate videos',
'guild wars 2 intermediate lessons',
'guild wars 2 intermediate tactics',
'guild wars 2 intermediate overview',
'guild wars 2 intermediate tips and trick',
'guild wars 2 intermediate gameplay',
'guild wars 2 intermediate common mistakes',
'guild wars 2 intermediate builds',
'guild wars 2 intermediate players',
'guild wars 2 intermediate noobs',
'guild wars 2 intermediate news',
'guild wars 2 intermediate tutorial',
'guild wars 2 expert guide',
'guild wars 2 expert tutorial',
'guild wars 2 expert strategy',
'guild wars 2 expert methods',
'guild wars 2 expert lessons',
'guild wars 2 expert techniques',
'guild wars 2 expert videos',
'guild wars 2 expert lessons',
'guild wars 2 expert tactics',
'guild wars 2 expert overview',
'guild wars 2 expert tips and trick',
'guild wars 2 expert gameplay',
'guild wars 2 expert common mistakes',
'guild wars 2 expert builds',
'guild wars 2 expert players',
'guild wars 2 expert noobs',
'guild wars 2 expert news',
'guild wars 2 expert tutorial',
'guild wars 2 pro guide',
'guild wars 2 pro tutorial',
'guild wars 2 pro strategy',
'guild wars 2 pro methods',
'guild wars 2 pro lessons',
'guild wars 2 pro techniques',
'guild wars 2 pro videos',
'guild wars 2 pro lessons',
'guild wars 2 pro tactics',
'guild wars 2 pro overview',
'guild wars 2 pro tips and trick',
'guild wars 2 pro gameplay',
'guild wars 2 pro common mistakes',
'guild wars 2 pro builds',
'guild wars 2 pro players',
'guild wars 2 pro noobs',
'guild wars 2 pro news',
'guild wars 2 pro tutorial',
'neverwinter beginner guide',
'neverwinter beginner tutorial',
'neverwinter beginner strategy',
'neverwinter beginner methods',
'neverwinter beginner lessons',
'neverwinter beginner techniques',
'neverwinter beginner videos',
'neverwinter beginner lessons',
'neverwinter beginner tactics',
'neverwinter beginner overview',
'neverwinter beginner tips and trick',
'neverwinter beginner gameplay',
'neverwinter beginner common mistakes',
'neverwinter beginner builds',
'neverwinter beginner players',
'neverwinter beginner noobs',
'neverwinter beginner news',
'neverwinter tutorial',
'neverwinter intermediate guide',
'neverwinter intermediate tutorial',
'neverwinter intermediate strategy',
'neverwinter intermediate methods',
'neverwinter intermediate lessons',
'neverwinter intermediate techniques',
'neverwinter intermediate videos',
'neverwinter intermediate lessons',
'neverwinter intermediate tactics',
'neverwinter intermediate overview',
'neverwinter intermediate tips and trick',
'neverwinter intermediate gameplay',
'neverwinter intermediate common mistakes',
'neverwinter intermediate builds',
'neverwinter intermediate players',
'neverwinter intermediate noobs',
'neverwinter intermediate news',
'neverwinter intermediate tutorial',
'neverwinter expert guide',
'neverwinter expert tutorial',
'neverwinter expert strategy',
'neverwinter expert methods',
'neverwinter expert lessons',
'neverwinter expert techniques',
'neverwinter expert videos',
'neverwinter expert lessons',
'neverwinter expert tactics',
'neverwinter expert overview',
'neverwinter expert tips and trick',
'neverwinter expert gameplay',
'neverwinter expert common mistakes',
'neverwinter expert builds',
'neverwinter expert players',
'neverwinter expert noobs',
'neverwinter expert news',
'neverwinter expert tutorial',
'neverwinter pro guide',
'neverwinter pro tutorial',
'neverwinter pro strategy',
'neverwinter pro methods',
'neverwinter pro lessons',
'neverwinter pro techniques',
'neverwinter pro videos',
'neverwinter pro lessons',
'neverwinter pro tactics',
'neverwinter pro overview',
'neverwinter pro tips and trick',
'neverwinter pro gameplay',
'neverwinter pro common mistakes',
'neverwinter pro builds',
'neverwinter pro players',
'neverwinter pro noobs',
'neverwinter pro news',
'neverwinter pro tutorial',
'maplestory beginner guide',
'maplestory beginner tutorial',
'maplestory beginner strategy',
'maplestory beginner methods',
'maplestory beginner lessons',
'maplestory beginner techniques',
'maplestory beginner videos',
'maplestory beginner lessons',
'maplestory beginner tactics',
'maplestory beginner overview',
'maplestory beginner tips and trick',
'maplestory beginner gameplay',
'maplestory beginner common mistakes',
'maplestory beginner builds',
'maplestory beginner players',
'maplestory beginner noobs',
'maplestory beginner news',
'maplestory tutorial',
'maplestory intermediate guide',
'maplestory intermediate tutorial',
'maplestory intermediate strategy',
'maplestory intermediate methods',
'maplestory intermediate lessons',
'maplestory intermediate techniques',
'maplestory intermediate videos',
'maplestory intermediate lessons',
'maplestory intermediate tactics',
'maplestory intermediate overview',
'maplestory intermediate tips and trick',
'maplestory intermediate gameplay',
'maplestory intermediate common mistakes',
'maplestory intermediate builds',
'maplestory intermediate players',
'maplestory intermediate noobs',
'maplestory intermediate news',
'maplestory intermediate tutorial',
'maplestory expert guide',
'maplestory expert tutorial',
'maplestory expert strategy',
'maplestory expert methods',
'maplestory expert lessons',
'maplestory expert techniques',
'maplestory expert videos',
'maplestory expert lessons',
'maplestory expert tactics',
'maplestory expert overview',
'maplestory expert tips and trick',
'maplestory expert gameplay',
'maplestory expert common mistakes',
'maplestory expert builds',
'maplestory expert players',
'maplestory expert noobs',
'maplestory expert news',
'maplestory expert tutorial',
'maplestory pro guide',
'maplestory pro tutorial',
'maplestory pro strategy',
'maplestory pro methods',
'maplestory pro lessons',
'maplestory pro techniques',
'maplestory pro videos',
'maplestory pro lessons',
'maplestory pro tactics',
'maplestory pro overview',
'maplestory pro tips and trick',
'maplestory pro gameplay',
'maplestory pro common mistakes',
'maplestory pro builds',
'maplestory pro players',
'maplestory pro noobs',
'maplestory pro news',
'maplestory pro tutorial',

    ]

if __name__ == '__main__':
    base_youtube_code.os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'
    client = base_youtube_code.get_authenticated_service()
    # NEED TO PASS IN CLIENT INTO FUNCTIONS!

    # get a list of channel IDs related to keywork

    for keyword in kw:
        print('keyword is: '+ keyword)
        channelId_list = keyword_search.run_keyword_search(client,keyword)

        # if channelId exist in database:
        # do not run

        for channelId in channelId_list:
            connection = sqlite3.connect('core.db')
            c = connection.cursor()
            creatorIdTuple = (channelId,)

            c.execute("""
                SELECT * FROM video
                WHERE creatorID = ?
                """, creatorIdTuple)

            existing_videoCount = c.fetchall()

            connection.commit()
            connection.close()

            # if there is a result in DB, have videos from creator saved
            if len(existing_videoCount) > 0:
                print('already discovered')
            # if results == 0, no videos saved from creator, just discovered a new creator
            else:
                videoId_list = get_channel_videos.run_get_channel_videos(client, channelId)
                for videoId in videoId_list:
                    video_statistics.run_video_statistics(client, videoId)
                print('new creator discovered')
                get_channel_stats.runStats(channelId)